### ISSUE TITLE
Similar project: sociomantic-tsunami/git-hub

### ISSUE THREAD

**Issue by jean** [jerriep/github-issues-cli#23]
It looks like you might be able to find some ideas and inspiration in 
https://github.com/sociomantic-tsunami/git-hub

I especially like being able to wrangle pull requests from the commandline.

**Comment by jerriep** [comment]
Thank for the link - I'll look into it. 

Though, for now, the scope of this project is limited to managing Issues only. I do not have any immediate plans to extend the scope beyond that to things like managing PRs
